CREATE TABLE people (
    id INT AUTO_INCREMENT PRIMARY KEY,
    user_id INT NOT NULL,
    name VARCHAR(100) NOT NULL,
    email VARCHAR(100) NOT NULL,
    phone VARCHAR(100) NOT NULL,
    CONSTRAINT fk_people_user_id FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
);